lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views  #1
from lists import urls as list_urls  #2

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    # url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.db import models

# Create your models here.
class List(models.Model):
    pass
class Item(models.Model):
    status = models.TextField(default='')
    tebakan = models.IntegerField(default=0)
    random = models.IntegerField(default=0)
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List
from random import randint

def home_page(request):
    return render(request, 'home.html')

def new_list(request):
    list_ = List.objects.create()

    rand = randint(1,30)
    nilaitebakan = int(request.POST['item_text'])
    hasil = cek(rand, nilaitebakan)
    Item.objects.create(tebakan=nilaitebakan, random=rand, status=hasil, list=list_)
    return redirect('/lists/%d/' % (list_.id,))

def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    rand = randint(1,30)
    nilaitebakan = int(request.POST['item_text'])
    hasil = cek(rand, nilaitebakan)
    Item.objects.create(tebakan=nilaitebakan, random=rand, status=hasil, list=list_)
    return redirect('/lists/%d/' % (list_.id,))

def cek(random, tebakan):
    if (tebakan >= (random-2))and(tebakan <= (tebakan+2)):
        return 'kamu menang'
    else:
        return 'kalah'

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    komentar = statkomen(list_)
    return render(request, 'list.html', {'list': list_, 'komentar': komentar})

def statkomen(list_):
    list = Item.objects.filter(list=list_).reverse()
    counter = 0
    komentar =''

    if len(list) < 3:
        return komentar
    
    for i in range(3):
        item = list[i]
        if item.status == 'kamu menang':
            counter = counter + 1

    if counter == 3:
        komentar = 'Ulala!!'

    counter = 0

    if len(list) < 5:
        return komentar
    
    for i in range(5):
        item = list[i]
        if item.status == 'kamu menang':
            counter = counter + 1

    if counter == 5:
        komentar = 'Ulalala'

    counter = 0   
    
    if len(list) < 10:
        return komentar
    
    for i in range(10):
        item = list[i]
        if item.status == 'kamu menang':
            counter = counter + 1

    if counter == 10:
        komentar = 'Uulala'

    return komentar

lists/templates/home.html
<html>
    <head>
        <title>To-Do lists</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
        <form method="POST" action="/lists/new">
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
            {% csrf_token %}
        </form>
    </body>
</html>

lists/templates/list.html
<html>
    <head>
        <title>To-Do lists</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
        <form method="POST" action="/lists/{{ list.id }}/add_item">
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
            {% csrf_token %}
        </form>

        <h4>{{ komentar }}</h4>
        <table id="id_list_table">
            {% for item in list.item_set.all %}
                <tr><td>{{ forloop.counter }}: {{ item.tebakan }}</td></tr>
                <tr><td>{{ forloop.counter }}: {{ item.random }}</td></tr>
                <tr><td>{{ forloop.counter }}: {{ item.status }}</td></tr>
            {% endfor %}
        </table>
    </body>
</html>